version: "3"
services:
  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/development/Dockerfile
      args:
        - NODE_ENV=development
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - ./logs/frontend:/root/.npm/_logs
      - ./.env:/app/.env
    networks:
      - internal
    ports:
      - "2703:3000"
    depends_on:
      - backend

  backend:
    container_name: ${PROJECT_SLUG}_backend
    build:
      context: .
      dockerfile: ./docker/backend/development/Dockerfile
      args:
        - NODE_ENV=development
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./.env:/app/.env
    networks:
      - internal
    ports:
      - "2704:3002"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - internal

volumes:
  postgres-data:

networks:
  internal:
    name: ${PROJECT_SLUG}_internal
    driver: bridge
