version: "3"
services:
  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/production/Dockerfile
      args:
        - NODE_ENV=production
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal
    ports:
      - "2703:3000"
    depends_on:
      - backend

  backend:
    container_name: ${PROJECT_SLUG}_backend
    build:
      context: .
      dockerfile: ./docker/backend/production/Dockerfile
      args:
        - NODE_ENV=production
    volumes:
      - ./backend/public/images:/backend/public/images
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal
    ports:
      - "2704:3002"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - internal

volumes:
  postgres-data:

networks:
  internal:
    name: ${PROJECT_SLUG}_internal
    driver: bridge
